
public enum TokenType {
    WORD, NUMBER, SEPERATOR, FOR, DO, WHILE, IF, BREAK, 
    CONTINUE, ELSE, RETURN, BEGIN, END, PRINT, PRINTF, 
    NEXT, IN, DELETE, GETLINE, EXIT, NEXTFILE, FUNCTION,
    STRINGLITERAL
}
